included:
  - './**/*.swift'

excluded:
  - Pods
  - fastlane
  - .build
  - build
  - DerivedData
  - Tests

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - missing_docs

# Rule configurations
cyclomatic_complexity:
  warning: 15
  error: 25

# Reporter type
reporter: "xcode"

